apiVersion: v1
kind: Service
metadata:
  name: web-nodeport
  labels:
    component: web-nodeport
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30010
      name: http
  selector:
    component: web